[target.x86_64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main"
pre-build = ["apt-get update && apt-get install -y protobuf-compiler cmake nasm libclang-dev pkg-config libssl-dev"]

[target.x86_64-unknown-linux-musl]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-musl:main"
pre-build = ["apt-get update && apt-get install -y protobuf-compiler cmake nasm libclang-dev musl-tools pkg-config libssl-dev"]

[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main"
pre-build = ["dpkg --add-architecture arm64 || true", "apt-get update && apt-get install -y protobuf-compiler cmake nasm libclang-dev pkg-config"]

